#!/usr/bin/env bash
# Sync container/shared/*.ts into each runner's src/ before tsc.
# This is the build-time copy step that lets us keep one canonical
# source for code shared across runners while still satisfying each
# tsconfig's strict rootDir setting.
#
# DO NOT edit the copied files. Edit the originals in container/shared/
# and rerun `npm run build`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHARED_DIR="$ROOT/shared"

declare -a TARGETS=(
  "$ROOT/agent-runner/src"
  "$ROOT/agent-runner-ghc/src"
)

# Files to sync (basename only; will be copied into each TARGET dir).
declare -a FILES=(
  "memory-tools.ts"
)

for target in "${TARGETS[@]}"; do
  if [[ ! -d "$target" ]]; then
    echo "warn: target dir missing: $target" >&2
    continue
  fi
  for f in "${FILES[@]}"; do
    src="$SHARED_DIR/$f"
    dst="$target/$f"
    if [[ ! -f "$src" ]]; then
      echo "warn: source missing: $src" >&2
      continue
    fi
    # Header banner + content; banner makes accidental edits obvious.
    {
      echo "// AUTO-GENERATED by container/shared/sync.sh — DO NOT EDIT"
      echo "// Source of truth: container/shared/$f"
      cat "$src"
    } > "$dst.tmp"
    mv "$dst.tmp" "$dst"
  done
done
